export const SET_RSVP_MODAL_VISIBLE = 'SET_RSVP_MODAL_VISIBLE';
export const SET_ADMIN_MENU_VISIBLE = 'SET_ADMIN_MENU_VISIBLE';
export const SET_ENV = 'SET_ENV';
export const SET_PICTURES_VISIBLE = 'SET_PICTURES_VISIBLE';
export const SET_RSVPS = 'SET_RSVPS';
export const SET_PICTURES = 'SET_PICTURES';